version: '3.9'

services:
  webserver:
    container_name: kirby-vue-dev
    build:
      context: ./web
      dockerfile: ./Dokerfile.dev
    restart: always
    environment:
      USERID: '1000' #user id of developing user
    network_mode: host
    ports:
    - "80:80"
    volumes:
    - ./web:/var/www/html:rw