version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: ./Dockerfile.dev
      args:
        - UID=1000 #dev user uuid
    restart: always
    ports:
    - "1312:80"
    volumes:
    - ./web:/var/www/html:rw