version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: ./Dockerfile.dev
    restart: always
    environment:
      USERID: '1000' #user id of developing user
    ports:
    - "1312:80"
    volumes:
    - ./web:/var/www/html:rw